# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-01 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location_friendly_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='location_gmaps_place_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
