# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-12 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0005_auto_20180412_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='subscriptions',
            field=models.ManyToManyField(through='newsletter.Subscription', to='newsletter.Category'),
        ),
    ]
