# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-11 07:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20171208_0934'),
        ('events', '0009_event_source'),
    ]

    operations = [
    ]
