# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-03 20:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name_plural': 'Subscribers'},
        ),
    ]
