# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-04 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_auto_20171203_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='tag',
            field=models.CharField(default='coming-soon', max_length=50),
            preserve_default=False,
        ),
    ]
