# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-12 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_category_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='mailchimp_list_id',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
