# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-12 07:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0004_category_mailchimp_list_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletter.Category')),
            ],
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='subscriptions',
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletter.Subscriber'),
        ),
    ]
